"use client";

import { useState } from "react";
import axios from "axios";
import { useAuth } from "@/context/AuthContext";

const API = "https://ai-data-dashboard.onrender.com";

interface Message {
  role: "user" | "assistant";
  content: string;
}

interface Props {
  datasetId: string;
  filename: string;
  rows: number;
  columns: string[];
  columnTypes: Record<string, "numeric" | "categorical" | "datetime">;
  messages: Message[];
}

export default function ExportReport({ datasetId, filename, rows, columns, columnTypes, messages }: Props) {
  const { token } = useAuth(); // Fix 1: Added token to authorize the AI summary request
  const [loading, setLoading] = useState(false);

  const generateReport = async () => {
    if (!token) {
      alert("Please log in again to export reports.");
      return;
    }
    
    setLoading(true);
    try {
      // Fix 2: Added Authorization header to the axios call
      const res = await axios.post(`${API}/api/query`, {
        dataset_id: datasetId,
        question: "Give me a comprehensive analysis of this dataset. Include: 1) What this dataset is about, 2) Key statistics and patterns, 3) Notable findings, 4) Any recommendations. Be thorough but concise.",
        history: [],
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });

      const summary = res.data.answer;
      const numericCols = columns.filter(c => columnTypes[c] === "numeric");

      // Build HTML report
      const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Data Analysis Report - ${filename}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px; color: #1f2937; max-width: 850px; margin: 0 auto; }
    h1 { color: #111827; border-bottom: 3px solid #6366f1; padding-bottom: 10px; }
    .meta { color: #6b7280; font-size: 14px; margin-bottom: 30px; }
    h2 { font-size: 18px; margin: 25px 0 10px; border-left: 4px solid #6366f1; padding-left: 10px; }
    .stats-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin-bottom: 25px; }
    .stat-card { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 15px; text-align: center; }
    .stat-value { font-size: 24px; font-weight: bold; color: #6366f1; }
    .summary { background: #f9fafb; border: 1px solid #e5e7eb; padding: 20px; border-radius: 8px; line-height: 1.6; white-space: pre-wrap; }
    .message { margin-bottom: 10px; padding: 10px; border-radius: 8px; font-size: 14px; }
    .user-msg { background: #eef2ff; border-left: 4px solid #6366f1; }
    .assistant-msg { background: #f0fdf4; border-left: 4px solid #10b981; }
    footer { margin-top: 40px; text-align: center; font-size: 12px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 20px; }
    @media print { .no-print { display: none; } }
  </style>
</head>
<body>
  <h1>📊 Data Analysis Report</h1>
  <div class="meta">File: <strong>${filename}</strong> &nbsp;·&nbsp; Generated: ${new Date().toLocaleString()}</div>

  <h2>Dataset Overview</h2>
  <div class="stats-grid">
    <div class="stat-card"><div class="stat-value">${rows.toLocaleString()}</div><div>Rows</div></div>
    <div class="stat-card"><div class="stat-value">${columns.length}</div><div>Columns</div></div>
    <div class="stat-card"><div class="stat-value">${numericCols.length}</div><div>Numeric</div></div>
  </div>

  <h2>AI Analysis Summary</h2>
  <div class="summary">${summary}</div>

  ${messages.length > 0 ? `
    <h2>Recent Chat Context</h2>
    ${messages.map(m => `
      <div class="message ${m.role === "user" ? "user-msg" : "assistant-msg"}">
        <strong>${m.role === "user" ? "You" : "AI Analyst"}:</strong><br/>${m.content}
      </div>
    `).join("")}
  ` : ""}

  <footer>Generated by AI Data Dashboard</footer>
</body>
</html>`;

      // Fix 3: Handle browser pop-up blockers by creating a Blob instead of window.open("")
      const blob = new Blob([html], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const win = window.open(url, "_blank");
      
      if (win) {
        win.focus();
        // Trigger print after the content is rendered
        win.onload = () => {
          setTimeout(() => {
            win.print();
            URL.revokeObjectURL(url);
          }, 500);
        };
      } else {
        alert("Pop-up blocked! Please allow pop-ups for this site to view the report.");
      }

    } catch (e) {
      console.error("Report Error:", e);
      alert("AI took too long to analyze. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      onClick={generateReport}
      disabled={loading}
      className="flex items-center gap-2 bg-gray-800 hover:bg-gray-700 disabled:bg-gray-800 disabled:text-gray-500 border border-gray-700 text-white text-sm font-medium px-4 py-2.5 rounded-xl transition"
    >
      {loading ? (
        <>
          <div className="w-4 h-4 border-2 border-indigo-400 border-t-transparent rounded-full animate-spin" />
          Generating Analysis...
        </>
      ) : (
        <>📄 Export Report</>
      )}
    </button>
  );
}